services:
  isdb-scanner:
    container_name: ISDBScanner
    build:
      context: ./src/ISDBScanner
    volumes:
      - ./config/Scanned:/app/Scanned
      - ./src/ISDBScanner/entrypoint.sh:/app/entrypoint.sh:ro
    command: [/bin/bash, /app/entrypoint.sh]
    entrypoint: ""
    restart: no

    # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================
    environment:
      - EXCLUDE_PAY_TV=1 # 1 にすると有料放送を除外します
    # 接続されている全てのデバイスにアクセスする必要があるため、特権モードを有効にする設定。
    privileged: true
    # セキュリティ上の都合で特権モードを利用したくない場合は
    # ホストマシンに接続されている TV チューナーとカードリーダーのデバイスファイルを個別に指定してください。
    # devices:
    #   - /dev/bus:/dev/bus
    #   - /dev/px4video0:/dev/px4video0
    #   - /dev/px4video1:/dev/px4video1
    #   - /dev/px4video2:/dev/px4video2
    #   - /dev/px4video3:/dev/px4video3
    #   - /dev/px4video4:/dev/px4video4
    #   - /dev/px4video5:/dev/px4video5
    #   - /dev/px4video6:/dev/px4video6
    #   - /dev/px4video7:/dev/px4video7
    # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================

  config-setup:
    container_name: ConfigSetup
    build:
      context: ./src
    volumes:
      - ./config:/app/config
    depends_on:
      isdb-scanner:
        condition: service_completed_successfully
    restart: no

    # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================
    # 接続されている全てのデバイスにアクセスする必要があるため、特権モードを有効にする設定。
    privileged: true
    # セキュリティ上の都合で特権モードを利用したくない場合は
    # ホストマシンに接続されている TV チューナーとカードリーダーのデバイスファイルを個別に指定してください。
    # devices:
    #   - /dev/bus:/dev/bus
    #   - /dev/px4video0:/dev/px4video0
    #   - /dev/px4video1:/dev/px4video1
    #   - /dev/px4video2:/dev/px4video2
    #   - /dev/px4video3:/dev/px4video3
    #   - /dev/px4video4:/dev/px4video4
    #   - /dev/px4video5:/dev/px4video5
    #   - /dev/px4video6:/dev/px4video6
    #   - /dev/px4video7:/dev/px4video7
    # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================

  mirakurun:
    container_name: Mirakurun
    build:
      context: ./src/Mirakurun
    ports:
      - 40772:40772
    expose:
      - 9229
    volumes:
      - ./config/Scanned/Mirakurun/channels.yml:/app-config/channels.yml:ro
      - ./config/Scanned/Mirakurun/tuners.yml:/app-config/tuners.yml:ro
      - ./config/Mirakurun/server.yml:/app-config/server.yml
      - ./src/Mirakurun/healthcheck.sh:/app/healthcheck.sh:ro
      - mirakurun-data:/app-data
      - mirakurun-socket:/var/run/mirakurun
    environment:
      TZ: Asia/Tokyo
    depends_on:
      isdb-scanner:
        condition: service_completed_successfully
      config-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: [CMD, /bin/bash, healthcheck.sh]
      interval: 5m
      timeout: 2s
      retries: 3
      start_period: 1m
      start_interval: 2s

    # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================
    # 接続されている全てのデバイスにアクセスする必要があるため、特権モードを有効にする設定。
    privileged: true
    # セキュリティ上の都合で特権モードを利用したくない場合は
    # ホストマシンに接続されている TV チューナーとカードリーダーのデバイスファイルを個別に指定してください。
    # devices:
    #   - /dev/bus:/dev/bus
    #   - /dev/px4video0:/dev/px4video0
    #   - /dev/px4video1:/dev/px4video1
    #   - /dev/px4video2:/dev/px4video2
    #   - /dev/px4video3:/dev/px4video3
    #   - /dev/px4video4:/dev/px4video4
    #   - /dev/px4video5:/dev/px4video5
    #   - /dev/px4video6:/dev/px4video6
    #   - /dev/px4video7:/dev/px4video7
    # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================

  edcb:
    container_name: EDCB
    build:
      context: ./src/EDCB
    ports:
      - "5510:5510"
      - "4510:4510"
    expose:
      - 4510
    volumes:
      - edcb-epg-data:/var/local/edcb/Setting
      - tv-record-data:/record/TV-Record
      - ./config/Scanned/EDCB/BonDriver_LinuxMirakc_S(LinuxMirakc).ChSet4.txt:/var/local/edcb/Setting/BonDriver_LinuxMirakc_S(LinuxMirakc).ChSet4.txt:ro
      - ./config/Scanned/EDCB/BonDriver_LinuxMirakc_T(LinuxMirakc).ChSet4.txt:/var/local/edcb/Setting/BonDriver_LinuxMirakc_T(LinuxMirakc).ChSet4.txt:ro
      - ./config/Scanned/EDCB/BonDriver_LinuxMirakc(LinuxMirakc).ChSet4.txt:/var/local/edcb/Setting/BonDriver_LinuxMirakc(LinuxMirakc).ChSet4.txt:ro
      - ./config/Scanned/EDCB/ChSet5.txt:/var/local/edcb/Setting/ChSet5.txt:ro
      - ./config/EDCB/Common.ini:/var/local/edcb/Common.ini
      - ./config/EDCB/EpgDataCap_Bon.ini:/var/local/edcb/EpgDataCap_Bon.ini
      - ./config/EDCB/EpgTimerSrv.ini:/var/local/edcb/EpgTimerSrv.ini
      - ./config/EDCB/bat:/var/local/edcb/bat
      - ./config/EDCB/RecEnd.sh:/var/local/edcb/RecEnd.sh:ro
      - ./src/EDCB/healthcheck.sh:/var/local/edcb/healthcheck.sh:ro
      - mirakurun-socket:/var/run/mirakurun
    depends_on:
      mirakurun:
        condition: service_healthy
      config-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: [CMD, /bin/bash, healthcheck.sh]
      interval: 5m
      timeout: 2s
      retries: 3
      start_period: 1m
      start_interval: 2s

  edcb-fetcher:
    container_name: EDCBFetcher
    build:
      context: ./src/EDCBFetcher
    environment:
      - BASE_URL=http://edcb:5510
    depends_on:
      edcb:
        condition: service_healthy
    restart: no

  file-transfer-server:
    image: ghcr.io/fa0311/file-transfer-system/file-transfer-server:latest
    container_name: file-transfer-server
    environment:
      - PEER_SERVER_ADDR=192.168.70.2:50051
      - ROOT_DIR=/file-transfer-data
    volumes:
      - tv-record-data:/file-transfer-data/TV-Record
    ports:
      - "50051:50051"
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  file-transfer-init:
    container_name: file-transfer-init
    build:
      context: ./src/FileTransferInit
    volumes:
      - ./src/ConfigSetup/EDCB/RecEnd.sh:/app/RecEnd.sh:ro
      - tv-record-data:/record/TV-Record
    depends_on:
      file-transfer-server:
        condition: service_healthy
    restart: no

  # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - --path.rootfs=/host
      - --path.udev.data=/host/run/udev/data
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, -qO-, "http://localhost:9100/metrics"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 20s

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  mirakurun-exporter:
    image: ghcr.io/coord-e/mirakurun-exporter:latest
    container_name: mirakurun-exporter
    command:
      - --exporter.mirakurun-url=http://mirakurun:40772/
      - --exporter.status
      - --exporter.tuners
      - --exporter.services
    ports:
      - "9110:9110"
    depends_on:
      mirakurun:
        condition: service_healthy
    restart: unless-stopped
  # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================

volumes:
  mirakurun-data:
    name: mirakurun-data
  mirakurun-socket:
    name: mirakurun-socket
  edcb-epg-data:
    name: edcb-epg-data
  # ==================== ↓↓↓↓↓ ここからユーザー設定 ↓↓↓↓↓ ====================
  tv-record-data:
    name: tv-record-data
    driver: local
    driver_opts:
      type: none
      device: ./record/TV-Record
      o: bind
  portainer-data:
    name: portainer-data
  # ==================== ↑↑↑↑↑ ここまでユーザー設定 ↑↑↑↑↑ ====================
